import React from "react";
import type { Meta } from "@storybook/react";
import { Slider } from "./Slider";
import { SemanticColor } from "../../../core/system";
import { SliderDirection, SliderSizes } from "./constants";
declare const meta: Meta<typeof Slider>;
export default meta;
export declare const Primary: import("@storybook/csf").AnnotatedStoryFn<import("@storybook/react").ReactRenderer, {
    color?: SemanticColor;
    customColor?: string;
    customHoverColor?: string;
    size?: SliderSizes;
    label?: string;
    isDisabled?: boolean;
    direction?: SliderDirection;
    name?: string;
    blackText?: boolean;
    showSteps?: boolean;
    step?: number;
    maxValue?: number;
    startContent?: React.ReactNode;
    endContent?: React.ReactNode;
    value: number;
    maxWidth?: number;
    onChange: (value: number) => void;
}>;
export declare const Vertical: import("@storybook/csf").AnnotatedStoryFn<import("@storybook/react").ReactRenderer, {
    color?: SemanticColor;
    customColor?: string;
    customHoverColor?: string;
    size?: SliderSizes;
    label?: string;
    isDisabled?: boolean;
    direction?: SliderDirection;
    name?: string;
    blackText?: boolean;
    showSteps?: boolean;
    step?: number;
    maxValue?: number;
    startContent?: React.ReactNode;
    endContent?: React.ReactNode;
    value: number;
    maxWidth?: number;
    onChange: (value: number) => void;
}>;
export declare const WithLabels: import("@storybook/csf").AnnotatedStoryFn<import("@storybook/react").ReactRenderer, {
    color?: SemanticColor;
    customColor?: string;
    customHoverColor?: string;
    size?: SliderSizes;
    label?: string;
    isDisabled?: boolean;
    direction?: SliderDirection;
    name?: string;
    blackText?: boolean;
    showSteps?: boolean;
    step?: number;
    maxValue?: number;
    startContent?: React.ReactNode;
    endContent?: React.ReactNode;
    value: number;
    maxWidth?: number;
    onChange: (value: number) => void;
}>;
export declare const WithIcons: import("@storybook/csf").AnnotatedStoryFn<import("@storybook/react").ReactRenderer, {
    color?: SemanticColor;
    customColor?: string;
    customHoverColor?: string;
    size?: SliderSizes;
    label?: string;
    isDisabled?: boolean;
    direction?: SliderDirection;
    name?: string;
    blackText?: boolean;
    showSteps?: boolean;
    step?: number;
    maxValue?: number;
    startContent?: React.ReactNode;
    endContent?: React.ReactNode;
    value: number;
    maxWidth?: number;
    onChange: (value: number) => void;
}>;
export declare const WithSteps: import("@storybook/csf").AnnotatedStoryFn<import("@storybook/react").ReactRenderer, {
    color?: SemanticColor;
    customColor?: string;
    customHoverColor?: string;
    size?: SliderSizes;
    label?: string;
    isDisabled?: boolean;
    direction?: SliderDirection;
    name?: string;
    blackText?: boolean;
    showSteps?: boolean;
    step?: number;
    maxValue?: number;
    startContent?: React.ReactNode;
    endContent?: React.ReactNode;
    value: number;
    maxWidth?: number;
    onChange: (value: number) => void;
}>;
export declare const WithIconsSteps: import("@storybook/csf").AnnotatedStoryFn<import("@storybook/react").ReactRenderer, {
    color?: SemanticColor;
    customColor?: string;
    customHoverColor?: string;
    size?: SliderSizes;
    label?: string;
    isDisabled?: boolean;
    direction?: SliderDirection;
    name?: string;
    blackText?: boolean;
    showSteps?: boolean;
    step?: number;
    maxValue?: number;
    startContent?: React.ReactNode;
    endContent?: React.ReactNode;
    value: number;
    maxWidth?: number;
    onChange: (value: number) => void;
}>;
export declare const WithIconsStepsVertical: import("@storybook/csf").AnnotatedStoryFn<import("@storybook/react").ReactRenderer, {
    color?: SemanticColor;
    customColor?: string;
    customHoverColor?: string;
    size?: SliderSizes;
    label?: string;
    isDisabled?: boolean;
    direction?: SliderDirection;
    name?: string;
    blackText?: boolean;
    showSteps?: boolean;
    step?: number;
    maxValue?: number;
    startContent?: React.ReactNode;
    endContent?: React.ReactNode;
    value: number;
    maxWidth?: number;
    onChange: (value: number) => void;
}>;
export declare const Disabled: import("@storybook/csf").AnnotatedStoryFn<import("@storybook/react").ReactRenderer, {
    color?: SemanticColor;
    customColor?: string;
    customHoverColor?: string;
    size?: SliderSizes;
    label?: string;
    isDisabled?: boolean;
    direction?: SliderDirection;
    name?: string;
    blackText?: boolean;
    showSteps?: boolean;
    step?: number;
    maxValue?: number;
    startContent?: React.ReactNode;
    endContent?: React.ReactNode;
    value: number;
    maxWidth?: number;
    onChange: (value: number) => void;
}>;
