import type { Meta, StoryObj } from '@storybook/react';
import { Button } from './Button';
declare const meta: Meta<typeof Button>;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Primary: Story;
export declare const IsDisabled: Story;
export declare const DisabledRipple: Story;
export declare const GroupButtons: Story;
export declare const WithStartContent: Story;
export declare const WithEndContent: Story;
export declare const WithIcon: Story;
