import type { Meta, StoryObj } from "@storybook/react";
import { Progress } from "./Progress";
declare const meta: Meta<typeof Progress>;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Primary: Story;
export declare const WithLabel: Story;
export declare const WithValueLabel: Story;
export declare const ShowPercentageLabel: Story;
export declare const ShowPercentageLabelWithValueLabel: Story;
export declare const IsIndeterminate: Story;
