import type { Meta, StoryFn as Story } from "@storybook/react";
import { Input } from "./Input";
declare const meta: Meta<typeof Input>;
export default meta;
export declare const Default: Story;
export declare const Placeholder: Story;
export declare const Disabled: Story;
export declare const Password: Story;
export declare const Faded: Story;
export declare const Bordered: Story;
export declare const Underlined: Story;
export declare const ReadOnly: Story;
